### PR TITLE
Documentation setup and first draft

### PR DESCRIPTION
**Pull request by frgigr**
As just discussed in the [last WP2 meeting](https://agenda.infn.it/event/39693/), this PR provides the setup and a first draft of the documentation material, built with Jupyter Book.

GitHub Pages option has to be activated after merging (Settings -> Code and automation -> Pages), choosing the `docs` folder, from `main` branch, as input.

### CODE REVIEW

**Comment by frgigr** [comment]
Addressing pipeline issue

**Comment by frgigr** [comment]
The [sphinx-book-theme](https://pypi.org/project/sphinx-book-theme/) package was updated to version 1.1.1 2h ago, breaking the jupyter book compilation. Bug report sent [here](https://github.com/executablebooks/sphinx-book-theme/pull/814#issuecomment-1941968901). I'll wait for a fix, otherwise I'll revert back to 1.1.0 version

**Comment by frgigr** [comment]
The previous issue has been fixed, bumping [sphinx-book-theme](https://pypi.org/project/sphinx-book-theme/) package to version 1.1.2.  Build job succeeded!

**GitHub Pages activated**! The PR has to be merged, as GitHub pages have to be deployed from the main repository. Ready to be merged if there're no objection

**Comment by ttedeschi** [comment]
Merging since there are no further comments

**Pull request merged**
